-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 18:29:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Players` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Players` (
  `player_id` INT NOT NULL,
  `player_name` VARCHAR(100) NOT NULL,
  `position` VARCHAR(50) NOT NULL,
  `team_name` VARCHAR(50) NULL,
  PRIMARY KEY (`player_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameParticipants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameParticipants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameParticipants` (
  `season_number` INT NOT NULL,
  `game_number` INT NOT NULL,
  `team_name` VARCHAR(50) NOT NULL,
  `points_scored` INT NOT NULL,
  PRIMARY KEY (`season_number`, `game_number`, `team_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Games` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Games` (
  `season_number` INT NOT NULL,
  `game_number` INT NOT NULL,
  `winning_team_name` VARCHAR(50) NULL,
  `GameParticipants_season_number` INT NOT NULL,
  `GameParticipants_game_number` INT NOT NULL,
  `GameParticipants_team_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`season_number`, `game_number`, `GameParticipants_season_number`, `GameParticipants_game_number`, `GameParticipants_team_name`),
  INDEX `fk_Games_GameParticipants1_idx` (`GameParticipants_season_number` ASC, `GameParticipants_game_number` ASC, `GameParticipants_team_name` ASC) VISIBLE,
  CONSTRAINT `fk_Games_GameParticipants1`
    FOREIGN KEY (`GameParticipants_season_number` , `GameParticipants_game_number` , `GameParticipants_team_name`)
    REFERENCES `mydb`.`GameParticipants` (`season_number` , `game_number` , `team_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teams` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teams` (
  `team_name` VARCHAR(50) NOT NULL,
  `team_location` VARCHAR(150) NOT NULL,
  `Players_player_id` INT NOT NULL,
  `Games_season_number` INT NOT NULL,
  `Games_game_number` INT NOT NULL,
  `GameParticipants_season_number` INT NOT NULL,
  `GameParticipants_game_number` INT NOT NULL,
  `GameParticipants_team_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`team_name`),
  INDEX `fk_Teams_Players_idx` (`Players_player_id` ASC) VISIBLE,
  INDEX `fk_Teams_Games1_idx` (`Games_season_number` ASC, `Games_game_number` ASC) VISIBLE,
  INDEX `fk_Teams_GameParticipants1_idx` (`GameParticipants_season_number` ASC, `GameParticipants_game_number` ASC, `GameParticipants_team_name` ASC) VISIBLE,
  CONSTRAINT `fk_Teams_Players`
    FOREIGN KEY (`Players_player_id`)
    REFERENCES `mydb`.`Players` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_Games1`
    FOREIGN KEY (`Games_season_number` , `Games_game_number`)
    REFERENCES `mydb`.`Games` (`season_number` , `game_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_GameParticipants1`
    FOREIGN KEY (`GameParticipants_season_number` , `GameParticipants_game_number` , `GameParticipants_team_name`)
    REFERENCES `mydb`.`GameParticipants` (`season_number` , `game_number` , `team_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seasons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seasons` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Seasons` (
  `season_number` INT NOT NULL,
  `season_year` INT NOT NULL,
  `Games_season_number` INT NOT NULL,
  `Games_game_number` INT NOT NULL,
  PRIMARY KEY (`season_number`),
  INDEX `fk_Seasons_Games1_idx` (`Games_season_number` ASC, `Games_game_number` ASC) VISIBLE,
  CONSTRAINT `fk_Seasons_Games1`
    FOREIGN KEY (`Games_season_number` , `Games_game_number`)
    REFERENCES `mydb`.`Games` (`season_number` , `game_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
